# Configuration for fusion node
fusion_node:
  ros__parameters:
    # Verbose flag; Print additional information if true
    verbose: true
    # Print debug information
    debug: true
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5
    # Save debug data; output folder ros2_ws/install/fusion_node/share/fusion_node/data
    save_data: false
    # Depth scale for left camera in meters; uint16 value * depth scale = distance
    depth_scale_left: 0.001 # D455
    #depth_scale_left: 0.00025 # L515
    # Depth scale for right camera in meters; uint16 value * depth scale = distance
    depth_scale_right: 0.001 # D455
    #depth_scale_right: 0.00025 # L515
    # Minimum and maximum limit for depth values
    min_depth: 0.5
    max_depth: 3.0
    # If true output vertical image otherwise horizontal
    vertical_image: true
    # Mirror image horizontally if true
    mirror_image: true
    # Set virtual camera pose relative to left camera position
    # Axis X right, Y down, Z forward
    set_camera_pose: false
    # Virtual camera translation in meters
    camera_translation: [-1.0, 0.0, 0.0]
    # Virtual camera rotation around x,y,z axis in degrees
    camera_rotation: [0.0, 45.0, 0.0]
    # Profiling configuration
    profiling:
      # Enable profiling logging
      enable_profiling: false
      # Profiling logfile in current working directory
      filename: fusion_node_profiling.txt
      # Number of callbacks to log
      log_size: 400
